# Generated by Django 2.2.9 on 2020-11-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_authr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authr',
            new_name='author',
        ),
    ]
