# Generated by Django 2.2.9 on 2020-11-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201106_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
